from __future__ import annotations

from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = REPO_ROOT / "docs"
GENERATED_SHOWCASE = (DOCS_ROOT / "tutorial" / "tui-showcase").resolve()


class _DocumentParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.references: list[str] = []
        self.ids: set[str] = set()

    def handle_starttag(
        self,
        tag: str,
        attrs: list[tuple[str, str | None]],
    ) -> None:
        values = dict(attrs)
        element_id = values.get("id")
        if element_id:
            self.ids.add(element_id)
        for attribute in ("href", "src"):
            reference = values.get(attribute)
            if reference:
                self.references.append(reference)


def _parse(path: Path) -> _DocumentParser:
    parser = _DocumentParser()
    parser.feed(path.read_text(encoding="utf-8"))
    return parser


def _resolve_html_target(source: Path, raw_path: str) -> Path:
    target = (source.parent / unquote(raw_path)).resolve()
    if raw_path.endswith("/"):
        target /= "index.html"
    return target


def test_documentation_internal_links_are_valid() -> None:
    pages = sorted(DOCS_ROOT.rglob("*.html"))
    assert pages, "documentation site must contain HTML pages"

    parsed = {page.resolve(): _parse(page) for page in pages}

    for source, document in parsed.items():
        for reference in document.references:
            parts = urlsplit(reference)
            if parts.scheme or parts.netloc:
                continue

            if parts.path:
                target = _resolve_html_target(source, parts.path)
                if target.is_relative_to(GENERATED_SHOWCASE):
                    # Deterministic SVGs are generated by capture_tui_showcase.py
                    # during local documentation builds and GitHub Pages deploys.
                    assert target.suffix == ".svg"
                    continue
                assert target.exists(), f"{source}: broken link {reference!r}"
            else:
                target = source

            if parts.fragment and target.suffix == ".html":
                target_document = parsed.get(target.resolve())
                assert target_document is not None, (
                    f"{source}: HTML target is outside documentation audit: {reference!r}"
                )
                assert parts.fragment in target_document.ids, (
                    f"{source}: missing anchor #{parts.fragment} in {target}"
                )
